# Generated by Django 6.0.4 on 2026-04-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_enrollment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
